// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lctpfdhpplkxgkyiugik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjdHBmZGhwcGxreGdreWl1Z2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDgwOTIsImV4cCI6MjA3MTg4NDA5Mn0.-o7jjVM1_2RKrfwd0xFM81H2UIdglz3qICDn_SatXhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});